# Generated by Django 2.1.1 on 2018-10-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0004_change_deletion_strategy_for_pet_and_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='owner',
        ),
    ]
