# Generated by Django 2.1.1 on 2018-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('rodent', 'Rodent')], default='dog', max_length=32),
        ),
    ]
